SdkException: Format message instead of overriding toString
It seems that the toString method is actually not really called (for example, ScalaTest did
not the print the full message).